baseurl = "http://kfreiman.github.io"
title = "Кирилл Фрейман"
languageCode = "ru-Ru"
MetaDataFormat = "toml"
theme = "slender"
paginate = 3
PaginatePath = "/"

[author]
    name = "Kirill Freiman"

[permalinks]

    # Permalink format for pages.
    page = "/:title/"

    # Permalink format for blog posts.
    post = "/article/:title/"

[params]

    # Change the color scheme of Slender.
    # See above for preview and list of color schemes.
    colorscheme = "white"

    # Tagline; HTML accepted here. Keep it concise.
    tagline = ""

    # Footer; Markdown accepted here.
    footer = "2016 &copy; Кирилл Фрейман"

    # Description and keywords for <meta> tags.
    # Remember to set this for your main page.
    # This will be overridden by whatever is set by the page or post,
    # defined by `description` and `keywords` variables in the front matter
    # of the markdown file.
    description = "Блог о культуре программистов"
    keywords = "культура программирования,технологический прогресс,технологии,технологическая сингулярность,Кирилл Фрейман,Open Source"

    # Social links, must be full URLs (e.g. https://github.com/CrimsonRay/).
    # Remove, comment, or leave blank any field to leave them out.
    email = "mailto:k.freiman@ya.ru"
    github = "https://github.com/kfreiman"
    # linkedin = "url-to-your-linkedin"
    facebook = "https://www.facebook.com/kirill.freiman"


[menu]

    # Menu for the nav bar.
    # There must always be one item present (e.g. home).
    [[menu.main]]
    identifier = "home"
    name       = "home"
    url        = "/"
    weight     = 0

    # [[menu.main]]
    # identifier = "about"
    # name       = "about"
    # url        = "/about/"
    # weight     = 1
